[FE] Header 구현
codestates-seb/seb40_main_012 pull request #23
Opened 2022-11-12 07:35 UTC by jwo0o0

<img width="953" alt="image" src="https://user-images.githubusercontent.com/70098708/201463046-aa42f75d-6db1-459e-81ca-d2c31ac4961a.png">

우선 이렇게 헤더 구현했습니다!
입력후 엔터누르면 검색 페이지로 가고 로그인, 마이페이지 url도 연결은 해놓았는데 라우터 정해지면 연결하시면 됩니다!

로그인/로그아웃은 로그인 상태 여부에 따라 보여지게 했는데 회의 때 얘기해보면 좋을 것 같아요:)

2022-11-12 08:33 UTC, jwo0o0 commented
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/70098708/201466011-c8cc414a-ace4-42d8-bcca-b692f962939a.png">

Footer 까지 일단 간단하게 구현했습니다!

2022-11-12 09:03 UTC, JinhuiKim requested changes
확인했습니다! 리뷰 내용 확인부탁드립니다.

2022-11-12 09:03 UTC, JinhuiKim commented on front/src/components/PageContainer.js
> +import Header from './Header_';
아예 Header, Footer를 개발해주신걸로 바꿔서 연결해주셔도 좋을 것 같아요!
기존 Header 파일은 Header_ 소스로 덮어써주시고 Footer 파일 추가하고 StickyFooter 파일은 지우셔도 됩니다

2022-11-13 10:46 UTC, jwo0o0 commented
PageContainer에 수정사항 반영했고 머지하겠습니다!

2022-11-13 10:46 UTC, merged